version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:1.0.0
    ports:
      - "80:8080"
    environment:
      - FLASK_ENV=development
      - PORT=8080
    volumes:
      - .:/app
    command: python app.py
    restart: unless-stopped
    