name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-ecr-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}  # używa 7 pierwszych znaków SHA commit
          docker build -t flask-app:${IMAGE_TAG} .
          docker tag flask-app:${IMAGE_TAG} ${{ secrets.ECR_REPO_URL }}:${IMAGE_TAG}

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push ${{ secrets.ECR_REPO_URL }}:${IMAGE_TAG}
